### ISSUE TITLE
Urgent Report!

### ISSUE THREAD

**Issue by KurisuMiyamoto** [Kamtheman56/Zelda_Mod#19]
I install the new verison of the mod, the 1.2.3 and it crashed even if it is the only mod installed!
[crash-2024-07-06_06.48.39-fml.txt](https://github.com/user-attachments/files/17364645/crash-2024-07-06_06.48.39-fml.txt)

**Comment by Kamtheman56** [comment]
Looking at your crash report your issue is due to a mod called Chunksending and it requiring Cupboard.
If you're only using Legendary Armory it requires ExpandAbility to function, but my mod and that don't seem to be the ones causing issues.

"Mod File: /C:/Users/USER/AppData/Roaming/.minecraft/mods/chunksending-1.20.1-2.8.jar
	Failure message: Mod chunksending requires cupboard 1.20.1-1.5 or above
		Currently, cupboard is not installed
	Mod Version: 1.20.1-2.8
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE"

**Comment by KurisuMiyamoto** [comment]
i was trying to delete the issue just now lol

**Comment by KurisuMiyamoto** [comment]
i notice it a few seconds ago

**Comment by Kamtheman56** [comment]
It's okay! Everyone makes mistakes, all you can do is learn from them. I would much rather their be an issue made known to me, so I can take a look rather than people just letting it crash without saying.
